export interface TilesetEntry {
  name: string;
  image: string;
}

export const WORLD_TILESETS: TilesetEntry[] = [
  { name: 'plains-modified', image: 'sprites/tilesets/plains-modified.png' },
  { name: 'Modern_Outside_B_Sheet', image: 'sprites/tilesets/Modern_Outside_B_Sheet.png' },
  { name: 'Modern_Outside_C_Sheet', image: 'sprites/tilesets/Modern_Outside_C_Sheet.png' },
  { name: 'non-rm-a4-square', image: 'sprites/tilesets/non-rm-a4-square.png' },
  { name: 'tournament-arena', image: 'sprites/tilesets/tournament-arena.png' },
  { name: 'arena2', image: 'sprites/tilesets/arena2.png' },
  { name: 'trees', image: 'sprites/tilesets/trees.png' },
  { name: 'paths', image: 'sprites/tilesets/paths.png' },
  { name: '$fountain', image: 'sprites/tilesets/$fountain.png' },
  { name: 'fountain', image: 'sprites/tilesets/fountain.png' },
  { name: 'chesstable', image: 'sprites/tilesets/chesstable.png' },
  { name: 'chessboard2', image: 'sprites/tilesets/chessboard2.png' },
  { name: 'chesstable3', image: 'sprites/tilesets/chesstable3.png' },
  { name: 'fountain2', image: 'sprites/tilesets/fountain2.png' },
  { name: 'floors2', image: 'sprites/tilesets/floors2.png' },
  { name: 'plantbox', image: 'sprites/tilesets/plantbox.png' },
  { name: 'Gothic_D', image: 'sprites/tilesets/Gothic_D.png' },
  { name: 'trees2', image: 'sprites/tilesets/trees2.png' },
  { name: 'parktree', image: 'sprites/tilesets/parktree.png' },
  { name: 'exterior', image: 'sprites/tilesets/exterior.png' },
  { name: 'tactics-academy', image: 'sprites/tilesets/tactics-academy.png' },
  { name: 'stairs1', image: 'sprites/tilesets/stairs1.png' },
  { name: 'weeklystats', image: 'sprites/tilesets/weeklystats.png' },
  { name: 'stones', image: 'sprites/tilesets/stones.png' },
  { name: 'seats', image: 'sprites/tilesets/seats.png' },
  { name: 'portal', image: 'sprites/tilesets/portal.png' },
  { name: 'water', image: 'sprites/tilesets/water.png' },
  { name: 'house1', image: 'sprites/tilesets/houses/house1.png' },
  { name: 'house2', image: 'sprites/tilesets/houses/house2.png' },
  { name: 'house3', image: 'sprites/tilesets/houses/house3.png' },
  { name: 'house4', image: 'sprites/tilesets/houses/house4.png' },
  { name: 'mansion1', image: 'sprites/tilesets/houses/mansion1.png' },
  { name: 'shop', image: 'sprites/tilesets/shop.png' },
  { name: 'analysis-school', image: 'sprites/tilesets/analysis-school.png' },
  { name: 'mansion2', image: 'sprites/tilesets/houses/mansion2.png' },
  { name: 'mansion3', image: 'sprites/tilesets/houses/mansion3.png' },
  { name: 'mansion4', image: 'sprites/tilesets/houses/mansion4.png' },
  { name: 'mansion5', image: 'sprites/tilesets/houses/mansion5.png' },
  { name: 'mansion6', image: 'sprites/tilesets/houses/mansion6.png' },
  { name: 'mansion7', image: 'sprites/tilesets/houses/mansion7.png' },
  { name: 'mansion8', image: 'sprites/tilesets/houses/mansion8.png' },
  { name: 'house5', image: 'sprites/tilesets/houses/house5.png' },
  { name: 'house6', image: 'sprites/tilesets/houses/house6.png' },
  { name: 'house7', image: 'sprites/tilesets/houses/house7.png' },
  { name: 'house8', image: 'sprites/tilesets/houses/house8.png' },
  { name: 'village-portal', image: 'sprites/tilesets/houses/village-portal.png' },
  { name: 'chessboard', image: 'sprites/tilesets/chessboard.png' },
  { name: 'analysis-school-bottom', image: 'sprites/tilesets/analysis-school-bottom.png' },
  { name: 'analysis-school-top', image: 'sprites/tilesets/analysis-school-top.png' },
  { name: 'shop-bottom', image: 'sprites/tilesets/shop-bottom.png' },
  { name: 'shop-top', image: 'sprites/tilesets/shop-top.png' },
  { name: 'tactics-academy-bottom', image: 'sprites/tilesets/tactics-academy-bottom.png' },
  { name: 'tactics-academy-top', image: 'sprites/tilesets/tactics-academy-top.png' },
  { name: 'portal-top', image: 'sprites/tilesets/portal-top.png' },
  { name: 'potal-bottom', image: 'sprites/tilesets/portal-bottom.png' },
];
